[project]
name = "generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faststream[nats]>=0.6.3",
    "msgspec>=0.20.0",
    "pydantic-settings>=2.12.0",
    "redis[hiredis]>=7.1.0",
]
